### PR TITLE
created comment model

### PR DESCRIPTION
**Pull request by goodritu1**
created  comment model

### CODE REVIEW

**Review by hunterthompson025 — CHANGES_REQUESTED** [review]
I would change the file name to Comment.js

Also the structure for the file is inconsistent with how the Car.js model is setup. Can you update the file to look the same way.

From the Car.js file

const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/connection');

class Car extends Model {}

**Comment by Nalipas** [comment]
looks good

**Review by hunterthompson025 — CHANGES_REQUESTED** [review]
The const Car line Is not needed for the model. If you remove line 4 it should be good.

**Review by hunterthompson025 — APPROVED** [review]
Looks good, thanks!

**Review by hunterthompson025 — APPROVED** [review]
Looks good

**Pull request merged**
